-- Migration 001: Player dialogue context
-- Creates the npc_player_context table to persist player-NPC relationship state
-- across sessions, and the RPC used by PlayerDialogueContextService.
--
-- The service calls:  client.Rpc<JObject>("get_player_dialogue_context",
--     { p_user_id = Guid, p_npc_slug = string|null })

-- ── Table ─────────────────────────────────────────────────────────────────────
create table if not exists public.npc_player_context (
    id              bigint generated by default as identity primary key,
    user_id         uuid not null references auth.users(id) on delete cascade,
    npc_slug        text not null,
    trust_score     int not null default 50,
    current_mood    text not null default 'neutral',
    dialogue_count  int not null default 0,
    clues           text[] not null default '{}',
    items           text[] not null default '{}',
    locations       text[] not null default '{}',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),

    -- Each user-npc pair has one row
    constraint npc_player_context_unique unique (user_id, npc_slug)
);

-- ── Indexes ───────────────────────────────────────────────────────────────────
create index if not exists idx_npc_player_context_user_id
    on public.npc_player_context (user_id);

-- ── Row-level security ────────────────────────────────────────────────────────
alter table public.npc_player_context enable row level security;

-- Users can read only their own contexts
create policy npc_player_context_select
    on public.npc_player_context for select
    using (auth.uid() = user_id);

-- Users can insert/update only their own contexts
create policy npc_player_context_insert
    on public.npc_player_context for insert
    with check (auth.uid() = user_id);

create policy npc_player_context_update
    on public.npc_player_context for update
    using (auth.uid() = user_id);

-- Users can delete their own contexts
create policy npc_player_context_delete
    on public.npc_player_context for delete
    using (auth.uid() = user_id);

-- ── Updated-at trigger ────────────────────────────────────────────────────────
create or replace function public.set_npc_player_context_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql security definer;

drop trigger if exists trg_npc_player_context_updated_at
    on public.npc_player_context;
create trigger trg_npc_player_context_updated_at
    before update on public.npc_player_context
    for each row execute function public.set_npc_player_context_updated_at();

-- ── RPC: get_player_dialogue_context ──────────────────────────────────────────
create or replace function public.get_player_dialogue_context(
    p_user_id    uuid,
    p_npc_slug   text default null
)
returns json
language plpgsql stable
as $$
declare
    result json;
begin
    select json_build_object(
        'player_name',  (select raw_user_meta_data ->> 'full_name' from auth.users where id = p_user_id),
        'trust_score',  ctx.trust_score,
        'current_mood', ctx.current_mood,
        'dialogue_count', ctx.dialogue_count,
        'clues',        coalesce(ctx.clues, '{}'),
        'items',        coalesce(ctx.items, '{}'),
        'locations',    coalesce(ctx.locations, '{}')
    )
    into result
    from public.npc_player_context ctx
    where ctx.user_id = p_user_id
      and (p_npc_slug is null or ctx.npc_slug = p_npc_slug);

    -- Return a sensible default if no context exists yet
    if result is null then
        result := json_build_object(
            'player_name',  (select raw_user_meta_data ->> 'full_name' from auth.users where id = p_user_id),
            'trust_score',  50,
            'current_mood', 'neutral',
            'dialogue_count', 0,
            'clues',        '{}',
            'items',        '{}',
            'locations',    '{}'
        );
    end if;

    return result;
end;
$$;

-- ── RPC: upsert_player_dialogue_context ───────────────────────────────────────
-- Called after each dialogue turn to persist updated trust / mood / clues state.
create or replace function public.upsert_player_dialogue_context(
    p_user_id        uuid,
    p_npc_slug       text,
    p_trust_score    int default null,
    p_current_mood   text default null,
    p_dialogue_count int default null,
    p_clues          text[] default null,
    p_items          text[] default null,
    p_locations      text[] default null
)
returns json
language plpgsql
as $$
declare
    result json;
begin
    insert into public.npc_player_context
        (user_id, npc_slug, trust_score, current_mood, dialogue_count, clues, items, locations)
    values (
        p_user_id,
        p_npc_slug,
        coalesce(p_trust_score, 50),
        coalesce(p_current_mood, 'neutral'),
        coalesce(p_dialogue_count, 0),
        coalesce(p_clues, '{}'),
        coalesce(p_items, '{}'),
        coalesce(p_locations, '{}')
    )
    on conflict (user_id, npc_slug) do update set
        trust_score    = coalesce(p_trust_score,    npc_player_context.trust_score),
        current_mood   = coalesce(p_current_mood,   npc_player_context.current_mood),
        dialogue_count = coalesce(p_dialogue_count, npc_player_context.dialogue_count),
        clues          = coalesce(p_clues,          npc_player_context.clues),
        items          = coalesce(p_items,          npc_player_context.items),
        locations      = coalesce(p_locations,      npc_player_context.locations),
        updated_at     = now()
    returning json_build_object(
        'trust_score',   trust_score,
        'current_mood',  current_mood,
        'dialogue_count', dialogue_count
    ) into result;

    return result;
end;
$$;
