// <auto-generated>Extracted from NPCDialogueUIController.cs for SRP</auto-generated>
using System.Linq;
using EditorAttributes;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace NPCSystem
{
    /// <content>Auto-find component references extracted from NPCDialogueUIController.</content>
    public partial class NPCDialogueUIController
    {
        [Button("Auto-Assign References")]
        void AutoAssignReferences()
        {
            ResolveReferences();
        }

        [Button("Validate UI References")]
        void ValidateUiReferences()
        {
            NPCFlowLogger
                .FindOrCreate()
                .Log(
                    NPCFlowStage.ConfigurationValidation,
                    dialogueManager != null ? NPCFlowStatus.Success : NPCFlowStatus.Warning,
                    dialogueManager != null ? NPCFlowLogLevel.Info : NPCFlowLogLevel.Warning,
                    dialogueManager != null
                        ? "NPCDialogueManager is assigned."
                        : "NPCDialogueManager is NOT assigned — runtime will not function.",
                    source: nameof(NPCDialogueUIController)
                );
        }

        void ResolveReferences()
        {
            if (dialogueManager == null)
            {
                dialogueManager = GetComponent<NPCDialogueManager>();
                if (dialogueManager == null)
                {
                    dialogueManager = FindAnyObjectByType<NPCDialogueManager>(
                        FindObjectsInactive.Include
                    );
                }
            }

            if (networkBridge == null)
            {
                networkBridge = GetComponent<NPCDialogueNetworkBridge>();
                if (networkBridge == null)
                {
                    networkBridge = FindAnyObjectByType<NPCDialogueNetworkBridge>(
                        FindObjectsInactive.Include
                    );
                }
            }

            if (legacyKnowledgeBaseController == null)
            {
                legacyKnowledgeBaseController = FindObjectsByType<Behaviour>(
                        FindObjectsInactive.Include
                    )
                    .FirstOrDefault(behaviour =>
                        behaviour != null
                        && behaviour.GetType().FullName == "LLMUnitySamples.KnowledgeBaseGame"
                    );
            }

            characterSelect =
                characterSelect != null
                    ? characterSelect
                    : FindComponent<TMP_Dropdown>("Canvas/Dropdown");
            playerInput =
                playerInput != null
                    ? playerInput
                    : FindComponent<TMP_InputField>("Canvas/PlayerInput");
            aiText = aiText != null ? aiText : FindComponent<TMP_Text>("Canvas/AIImage/AIText");
            stopButton =
                stopButton != null ? stopButton : FindComponent<Button>("Canvas/StopButton");

            butlerImage =
                butlerImage != null ? butlerImage : FindComponent<RawImage>("Canvas/ButlerImage");
            maidImage = maidImage != null ? maidImage : FindComponent<RawImage>("Canvas/MaidImage");
            chefImage = chefImage != null ? chefImage : FindComponent<RawImage>("Canvas/ChefImage");

            notebookController =
                notebookController != null
                    ? notebookController
                    : FindAnyObjectByType<NotebookUIController>(FindObjectsInactive.Include);
            exitButton =
                exitButton != null ? exitButton : FindComponent<Button>("Canvas/ExitButton");
        }
    }
}
